services:
    next:
        env_file:
            - .env
        build:
            context: ./app
            dockerfile: Dockerfiles/Dockerfile.local
        ports:
            - 3000:3000
        environment:
           NODE_ENV: production